// <auto-generated>
//     Generated by refactoring script during migration from Antelcat.I18N to WPFLocalizationExtension.
//     Manual edits may be overwritten.
// </auto-generated>

namespace StarResonanceDpsAnalysis.WPF.Properties;

public static class LocalizationKeys
{
    /// <summary>
    /// About_Community_GroupOne
    /// </summary>
    public const string About_Community_GroupOne = nameof(About_Community_GroupOne);
    /// <summary>
    /// About_Community_GroupTwo
    /// </summary>
    public const string About_Community_GroupTwo = nameof(About_Community_GroupTwo);
    /// <summary>
    /// About_Community_Invite
    /// </summary>
    public const string About_Community_Invite = nameof(About_Community_Invite);
    /// <summary>
    /// About_Contribution
    /// </summary>
    public const string About_Contribution = nameof(About_Contribution);
    /// <summary>
    /// About_Copyright
    /// </summary>
    public const string About_Copyright = nameof(About_Copyright);
    /// <summary>
    /// About_Developer_Ihonliu
    /// </summary>
    public const string About_Developer_Ihonliu = nameof(About_Developer_Ihonliu);
    /// <summary>
    /// About_Developer_Lead
    /// </summary>
    public const string About_Developer_Lead = nameof(About_Developer_Lead);
    /// <summary>
    /// About_Developer_QingLan
    /// </summary>
    public const string About_Developer_QingLan = nameof(About_Developer_QingLan);
    /// <summary>
    /// About_Developer_RocyJune
    /// </summary>
    public const string About_Developer_RocyJune = nameof(About_Developer_RocyJune);
    /// <summary>
    /// About_Developers_Label
    /// </summary>
    public const string About_Developers_Label = nameof(About_Developers_Label);
    /// <summary>
    /// About_Intro_Details
    /// </summary>
    public const string About_Intro_Details = nameof(About_Intro_Details);
    /// <summary>
    /// About_Intro_Primary
    /// </summary>
    public const string About_Intro_Primary = nameof(About_Intro_Primary);
    /// <summary>
    /// About_OpenSource_Prefix
    /// </summary>
    public const string About_OpenSource_Prefix = nameof(About_OpenSource_Prefix);
    /// <summary>
    /// About_OpenSource_RepositoryUrl
    /// </summary>
    public const string About_OpenSource_RepositoryUrl = nameof(About_OpenSource_RepositoryUrl);
    /// <summary>
    /// About_OpenSource_Suffix
    /// </summary>
    public const string About_OpenSource_Suffix = nameof(About_OpenSource_Suffix);
    /// <summary>
    /// About_PoweredBy
    /// </summary>
    public const string About_PoweredBy = nameof(About_PoweredBy);
    /// <summary>
    /// About_Thanks_Prefix
    /// </summary>
    public const string About_Thanks_Prefix = nameof(About_Thanks_Prefix);
    /// <summary>
    /// About_Thanks_RepositoryUrl
    /// </summary>
    public const string About_Thanks_RepositoryUrl = nameof(About_Thanks_RepositoryUrl);
    /// <summary>
    /// About_Thanks_Suffix
    /// </summary>
    public const string About_Thanks_Suffix = nameof(About_Thanks_Suffix);
    /// <summary>
    /// About_Version_Label
    /// </summary>
    public const string About_Version_Label = nameof(About_Version_Label);
    /// <summary>
    /// App_Name
    /// </summary>
    public const string App_Name = nameof(App_Name);
    /// <summary>
    /// Common_Action_Open
    /// </summary>
    public const string Common_Action_Open = nameof(Common_Action_Open);
    /// <summary>
    /// Common_Dash
    /// </summary>
    public const string Common_Dash = nameof(Common_Dash);
    /// <summary>
    /// DamageReference_Disclaimer
    /// </summary>
    public const string DamageReference_Disclaimer = nameof(DamageReference_Disclaimer);
    /// <summary>
    /// DamageReference_Header_Title
    /// </summary>
    public const string DamageReference_Header_Title = nameof(DamageReference_Header_Title);
    /// <summary>
    /// DamageReference_NoData
    /// </summary>
    public const string DamageReference_NoData = nameof(DamageReference_NoData);
    /// <summary>
    /// DamageReference_Profession_All
    /// </summary>
    public const string DamageReference_Profession_All = nameof(DamageReference_Profession_All);
    /// <summary>
    /// DamageReference_Ribbon_Title
    /// </summary>
    public const string DamageReference_Ribbon_Title = nameof(DamageReference_Ribbon_Title);
    /// <summary>
    /// DamageReference_Table_Title
    /// </summary>
    public const string DamageReference_Table_Title = nameof(DamageReference_Table_Title);
    /// <summary>
    /// Debug_AddSampleData
    /// </summary>
    public const string Debug_AddSampleData = nameof(Debug_AddSampleData);
    /// <summary>
    /// Debug_AddTestLog
    /// </summary>
    public const string Debug_AddTestLog = nameof(Debug_AddTestLog);
    /// <summary>
    /// Debug_AutoScroll
    /// </summary>
    public const string Debug_AutoScroll = nameof(Debug_AutoScroll);
    /// <summary>
    /// Debug_Button_About
    /// </summary>
    public const string Debug_Button_About = nameof(Debug_Button_About);
    /// <summary>
    /// Debug_Button_DamageReference
    /// </summary>
    public const string Debug_Button_DamageReference = nameof(Debug_Button_DamageReference);
    /// <summary>
    /// Debug_Button_PcapTest
    /// </summary>
    public const string Debug_Button_PcapTest = nameof(Debug_Button_PcapTest);
    /// <summary>
    /// Debug_Button_Settings
    /// </summary>
    public const string Debug_Button_Settings = nameof(Debug_Button_Settings);
    /// <summary>
    /// Debug_Button_SkillBreakdown
    /// </summary>
    public const string Debug_Button_SkillBreakdown = nameof(Debug_Button_SkillBreakdown);
    /// <summary>
    /// Debug_ClearLogs
    /// </summary>
    public const string Debug_ClearLogs = nameof(Debug_ClearLogs);
    /// <summary>
    /// Debug_Filter_Label
    /// </summary>
    public const string Debug_Filter_Label = nameof(Debug_Filter_Label);
    /// <summary>
    /// Debug_Filter_Level
    /// </summary>
    public const string Debug_Filter_Level = nameof(Debug_Filter_Level);
    /// <summary>
    /// Debug_Filter_Tooltip
    /// </summary>
    public const string Debug_Filter_Tooltip = nameof(Debug_Filter_Tooltip);
    /// <summary>
    /// Debug_Group_Title
    /// </summary>
    public const string Debug_Group_Title = nameof(Debug_Group_Title);
    /// <summary>
    /// Debug_Header_Category
    /// </summary>
    public const string Debug_Header_Category = nameof(Debug_Header_Category);
    /// <summary>
    /// Debug_Header_Level
    /// </summary>
    public const string Debug_Header_Level = nameof(Debug_Header_Level);
    /// <summary>
    /// Debug_Header_Message
    /// </summary>
    public const string Debug_Header_Message = nameof(Debug_Header_Message);
    /// <summary>
    /// Debug_Header_Time
    /// </summary>
    public const string Debug_Header_Time = nameof(Debug_Header_Time);
    /// <summary>
    /// Debug_LoadPcap
    /// </summary>
    public const string Debug_LoadPcap = nameof(Debug_LoadPcap);
    /// <summary>
    /// Debug_SaveLogs
    /// </summary>
    public const string Debug_SaveLogs = nameof(Debug_SaveLogs);
    /// <summary>
    /// Debug_Status_FilteredPrefix
    /// </summary>
    public const string Debug_Status_FilteredPrefix = nameof(Debug_Status_FilteredPrefix);
    /// <summary>
    /// Debug_Status_FilteredSuffix
    /// </summary>
    public const string Debug_Status_FilteredSuffix = nameof(Debug_Status_FilteredSuffix);
    /// <summary>
    /// Debug_Status_LastPrefix
    /// </summary>
    public const string Debug_Status_LastPrefix = nameof(Debug_Status_LastPrefix);
    /// <summary>
    /// Debug_Status_TotalPrefix
    /// </summary>
    public const string Debug_Status_TotalPrefix = nameof(Debug_Status_TotalPrefix);
    /// <summary>
    /// Debug_Status_TotalSuffix
    /// </summary>
    public const string Debug_Status_TotalSuffix = nameof(Debug_Status_TotalSuffix);
    /// <summary>
    /// Debug_ThemeTestText
    /// </summary>
    public const string Debug_ThemeTestText = nameof(Debug_ThemeTestText);
    /// <summary>
    /// DpsStatistics_TestButton_Content
    /// </summary>
    public const string DpsStatistics_TestButton_Content = nameof(DpsStatistics_TestButton_Content);
    /// <summary>
    /// DpsStatistics_TestButton_Tooltip
    /// </summary>
    public const string DpsStatistics_TestButton_Tooltip = nameof(DpsStatistics_TestButton_Tooltip);
    /// <summary>
    /// MainWindow_Debug_Button_About
    /// </summary>
    public const string MainWindow_Debug_Button_About = nameof(MainWindow_Debug_Button_About);
    /// <summary>
    /// MainWindow_Debug_Button_DamageReference
    /// </summary>
    public const string MainWindow_Debug_Button_DamageReference = nameof(MainWindow_Debug_Button_DamageReference);
    /// <summary>
    /// MainWindow_Debug_Button_PcapTest
    /// </summary>
    public const string MainWindow_Debug_Button_PcapTest = nameof(MainWindow_Debug_Button_PcapTest);
    /// <summary>
    /// MainWindow_Debug_Button_Settings
    /// </summary>
    public const string MainWindow_Debug_Button_Settings = nameof(MainWindow_Debug_Button_Settings);
    /// <summary>
    /// MainWindow_Debug_Button_SkillBreakdown
    /// </summary>
    public const string MainWindow_Debug_Button_SkillBreakdown = nameof(MainWindow_Debug_Button_SkillBreakdown);
    /// <summary>
    /// MainWindow_Debug_Group_Title
    /// </summary>
    public const string MainWindow_Debug_Group_Title = nameof(MainWindow_Debug_Group_Title);
    /// <summary>
    /// MainWindow_Debug_ThemeTest
    /// </summary>
    public const string MainWindow_Debug_ThemeTest = nameof(MainWindow_Debug_ThemeTest);
    /// <summary>
    /// MainWindow_Header_Title
    /// </summary>
    public const string MainWindow_Header_Title = nameof(MainWindow_Header_Title);
    /// <summary>
    /// MainWindow_Plugin_Author_OfficialTeam
    /// </summary>
    public const string MainWindow_Plugin_Author_OfficialTeam = nameof(MainWindow_Plugin_Author_OfficialTeam);
    /// <summary>
    /// MainWindow_Plugin_AutoStart
    /// </summary>
    public const string MainWindow_Plugin_AutoStart = nameof(MainWindow_Plugin_AutoStart);
    /// <summary>
    /// MainWindow_Plugin_DpsTool_Description
    /// </summary>
    public const string MainWindow_Plugin_DpsTool_Description = nameof(MainWindow_Plugin_DpsTool_Description);
    /// <summary>
    /// MainWindow_Plugin_DpsTool_Title
    /// </summary>
    public const string MainWindow_Plugin_DpsTool_Title = nameof(MainWindow_Plugin_DpsTool_Title);
    /// <summary>
    /// MainWindow_Plugin_Label_Author
    /// </summary>
    public const string MainWindow_Plugin_Label_Author = nameof(MainWindow_Plugin_Label_Author);
    /// <summary>
    /// MainWindow_Plugin_Label_Intro
    /// </summary>
    public const string MainWindow_Plugin_Label_Intro = nameof(MainWindow_Plugin_Label_Intro);
    /// <summary>
    /// MainWindow_Plugin_ModuleSolver_Description
    /// </summary>
    public const string MainWindow_Plugin_ModuleSolver_Description = nameof(MainWindow_Plugin_ModuleSolver_Description);
    /// <summary>
    /// MainWindow_Plugin_ModuleSolver_Title
    /// </summary>
    public const string MainWindow_Plugin_ModuleSolver_Title = nameof(MainWindow_Plugin_ModuleSolver_Title);
    /// <summary>
    /// MainWindow_Plugin_PigTracker_Description
    /// </summary>
    public const string MainWindow_Plugin_PigTracker_Description = nameof(MainWindow_Plugin_PigTracker_Description);
    /// <summary>
    /// MainWindow_Plugin_PigTracker_Title
    /// </summary>
    public const string MainWindow_Plugin_PigTracker_Title = nameof(MainWindow_Plugin_PigTracker_Title);
    /// <summary>
    /// MainWindow_Plugin_WorldBoss_Description
    /// </summary>
    public const string MainWindow_Plugin_WorldBoss_Description = nameof(MainWindow_Plugin_WorldBoss_Description);
    /// <summary>
    /// MainWindow_Plugin_WorldBoss_Title
    /// </summary>
    public const string MainWindow_Plugin_WorldBoss_Title = nameof(MainWindow_Plugin_WorldBoss_Title);
    /// <summary>
    /// MainWindow_PluginList_Title
    /// </summary>
    public const string MainWindow_PluginList_Title = nameof(MainWindow_PluginList_Title);
    /// <summary>
    /// Menu_Exit
    /// </summary>
    public const string Menu_Exit = nameof(Menu_Exit);
    /// <summary>
    /// Menu_History
    /// </summary>
    public const string Menu_History = nameof(Menu_History);
    /// <summary>
    /// Menu_PersonalMode
    /// </summary>
    public const string Menu_PersonalMode = nameof(Menu_PersonalMode);
    /// <summary>
    /// Menu_Record_Always
    /// </summary>
    public const string Menu_Record_Always = nameof(Menu_Record_Always);
    /// <summary>
    /// Menu_Record_Skip1Min
    /// </summary>
    public const string Menu_Record_Skip1Min = nameof(Menu_Record_Skip1Min);
    /// <summary>
    /// Menu_Record_Skip2Min
    /// </summary>
    public const string Menu_Record_Skip2Min = nameof(Menu_Record_Skip2Min);
    /// <summary>
    /// Menu_RecordSettings
    /// </summary>
    public const string Menu_RecordSettings = nameof(Menu_RecordSettings);
    /// <summary>
    /// Menu_Settings
    /// </summary>
    public const string Menu_Settings = nameof(Menu_Settings);
    /// <summary>
    /// Menu_ShowTotal
    /// </summary>
    public const string Menu_ShowTotal = nameof(Menu_ShowTotal);
    /// <summary>
    /// Menu_SkillDiary
    /// </summary>
    public const string Menu_SkillDiary = nameof(Menu_SkillDiary);
    /// <summary>
    /// Menu_SkillDisplay
    /// </summary>
    public const string Menu_SkillDisplay = nameof(Menu_SkillDisplay);
    /// <summary>
    /// Menu_SkillDisplay_All
    /// </summary>
    public const string Menu_SkillDisplay_All = nameof(Menu_SkillDisplay_All);
    /// <summary>
    /// Menu_SkillDisplay_Top10
    /// </summary>
    public const string Menu_SkillDisplay_Top10 = nameof(Menu_SkillDisplay_Top10);
    /// <summary>
    /// Menu_SkillDisplay_Top15
    /// </summary>
    public const string Menu_SkillDisplay_Top15 = nameof(Menu_SkillDisplay_Top15);
    /// <summary>
    /// Menu_SkillDisplay_Top5
    /// </summary>
    public const string Menu_SkillDisplay_Top5 = nameof(Menu_SkillDisplay_Top5);
    /// <summary>
    /// Menu_SkillDisplay_Top8
    /// </summary>
    public const string Menu_SkillDisplay_Top8 = nameof(Menu_SkillDisplay_Top8);
    /// <summary>
    /// Menu_StatisticBoss
    /// </summary>
    public const string Menu_StatisticBoss = nameof(Menu_StatisticBoss);
    /// <summary>
    /// Menu_Training
    /// </summary>
    public const string Menu_Training = nameof(Menu_Training);
    /// <summary>
    /// Menu_Training_Extreme
    /// </summary>
    public const string Menu_Training_Extreme = nameof(Menu_Training_Extreme);
    /// <summary>
    /// Menu_Training_Faction
    /// </summary>
    public const string Menu_Training_Faction = nameof(Menu_Training_Faction);
    /// <summary>
    /// Menu_Training_Personal
    /// </summary>
    public const string Menu_Training_Personal = nameof(Menu_Training_Personal);
    /// <summary>
    /// ModuleSolve_Analyze_Button
    /// </summary>
    public const string ModuleSolve_Analyze_Button = nameof(ModuleSolve_Analyze_Button);
    /// <summary>
    /// ModuleSolve_ExcludeProperties_Title
    /// </summary>
    public const string ModuleSolve_ExcludeProperties_Title = nameof(ModuleSolve_ExcludeProperties_Title);
    /// <summary>
    /// ModuleSolve_ExpectedLevel_Label
    /// </summary>
    public const string ModuleSolve_ExpectedLevel_Label = nameof(ModuleSolve_ExpectedLevel_Label);
    /// <summary>
    /// ModuleSolve_Header_Title
    /// </summary>
    public const string ModuleSolve_Header_Title = nameof(ModuleSolve_Header_Title);
    /// <summary>
    /// ModuleSolve_ModuleType_All
    /// </summary>
    public const string ModuleSolve_ModuleType_All = nameof(ModuleSolve_ModuleType_All);
    /// <summary>
    /// ModuleSolve_ModuleType_Defense
    /// </summary>
    public const string ModuleSolve_ModuleType_Defense = nameof(ModuleSolve_ModuleType_Defense);
    /// <summary>
    /// ModuleSolve_ModuleType_Label
    /// </summary>
    public const string ModuleSolve_ModuleType_Label = nameof(ModuleSolve_ModuleType_Label);
    /// <summary>
    /// ModuleSolve_ModuleType_Offense
    /// </summary>
    public const string ModuleSolve_ModuleType_Offense = nameof(ModuleSolve_ModuleType_Offense);
    /// <summary>
    /// ModuleSolve_ModuleType_Support
    /// </summary>
    public const string ModuleSolve_ModuleType_Support = nameof(ModuleSolve_ModuleType_Support);
    /// <summary>
    /// ModuleSolve_Property1_Label
    /// </summary>
    public const string ModuleSolve_Property1_Label = nameof(ModuleSolve_Property1_Label);
    /// <summary>
    /// ModuleSolve_Property2_Label
    /// </summary>
    public const string ModuleSolve_Property2_Label = nameof(ModuleSolve_Property2_Label);
    /// <summary>
    /// ModuleSolve_Property3_Label
    /// </summary>
    public const string ModuleSolve_Property3_Label = nameof(ModuleSolve_Property3_Label);
    /// <summary>
    /// ModuleSolve_Property4_Label
    /// </summary>
    public const string ModuleSolve_Property4_Label = nameof(ModuleSolve_Property4_Label);
    /// <summary>
    /// ModuleSolve_Property5_Label
    /// </summary>
    public const string ModuleSolve_Property5_Label = nameof(ModuleSolve_Property5_Label);
    /// <summary>
    /// ModuleSolve_Sort_Attribute
    /// </summary>
    public const string ModuleSolve_Sort_Attribute = nameof(ModuleSolve_Sort_Attribute);
    /// <summary>
    /// ModuleSolve_Sort_Label
    /// </summary>
    public const string ModuleSolve_Sort_Label = nameof(ModuleSolve_Sort_Label);
    /// <summary>
    /// ModuleSolve_Sort_Level
    /// </summary>
    public const string ModuleSolve_Sort_Level = nameof(ModuleSolve_Sort_Level);
    /// <summary>
    /// ModuleSolve_TargetProperties_Title
    /// </summary>
    public const string ModuleSolve_TargetProperties_Title = nameof(ModuleSolve_TargetProperties_Title);
    /// <summary>
    /// ModuleSolve_UsingTip
    /// </summary>
    public const string ModuleSolve_UsingTip = nameof(ModuleSolve_UsingTip);
    /// <summary>
    /// NumberDisplay_KMB
    /// </summary>
    public const string NumberDisplay_KMB = nameof(NumberDisplay_KMB);
    /// <summary>
    /// NumberDisplay_Wan
    /// </summary>
    public const string NumberDisplay_Wan = nameof(NumberDisplay_Wan);
    /// <summary>
    /// Profession_FrostMage
    /// </summary>
    public const string Profession_FrostMage = nameof(Profession_FrostMage);
    /// <summary>
    /// Profession_HeavyGuardian
    /// </summary>
    public const string Profession_HeavyGuardian = nameof(Profession_HeavyGuardian);
    /// <summary>
    /// Profession_Marksman
    /// </summary>
    public const string Profession_Marksman = nameof(Profession_Marksman);
    /// <summary>
    /// Profession_ShieldKnight
    /// </summary>
    public const string Profession_ShieldKnight = nameof(Profession_ShieldKnight);
    /// <summary>
    /// Profession_SoulMusician
    /// </summary>
    public const string Profession_SoulMusician = nameof(Profession_SoulMusician);
    /// <summary>
    /// Profession_Stormblade
    /// </summary>
    public const string Profession_Stormblade = nameof(Profession_Stormblade);
    /// <summary>
    /// Profession_VerdantOracle
    /// </summary>
    public const string Profession_VerdantOracle = nameof(Profession_VerdantOracle);
    /// <summary>
    /// Profession_WindKnight
    /// </summary>
    public const string Profession_WindKnight = nameof(Profession_WindKnight);
    /// <summary>
    /// Settings_Combat_ClearAfterBattle
    /// </summary>
    public const string Settings_Combat_ClearAfterBattle = nameof(Settings_Combat_ClearAfterBattle);
    /// <summary>
    /// Settings_Combat_ClearAfterTeleport
    /// </summary>
    public const string Settings_Combat_ClearAfterTeleport = nameof(Settings_Combat_ClearAfterTeleport);
    /// <summary>
    /// Settings_Common_Seconds
    /// </summary>
    public const string Settings_Common_Seconds = nameof(Settings_Common_Seconds);
    /// <summary>
    /// Settings_Display_NumberMode
    /// </summary>
    public const string Settings_Display_NumberMode = nameof(Settings_Display_NumberMode);
    /// <summary>
    /// Settings_Display_Opacity
    /// </summary>
    public const string Settings_Display_Opacity = nameof(Settings_Display_Opacity);
    /// <summary>
    /// Settings_Heading
    /// </summary>
    public const string Settings_Heading = nameof(Settings_Heading);
    /// <summary>
    /// Settings_Language_Auto
    /// </summary>
    public const string Settings_Language_Auto = nameof(Settings_Language_Auto);
    /// <summary>
    /// Settings_Language_Chinese
    /// </summary>
    public const string Settings_Language_Chinese = nameof(Settings_Language_Chinese);
    /// <summary>
    /// Settings_Language_English
    /// </summary>
    public const string Settings_Language_English = nameof(Settings_Language_English);
    /// <summary>
    /// Settings_NetworkAdapter_Label
    /// </summary>
    public const string Settings_NetworkAdapter_Label = nameof(Settings_NetworkAdapter_Label);
    /// <summary>
    /// Settings_Section_Basic_Sub
    /// </summary>
    public const string Settings_Section_Basic_Sub = nameof(Settings_Section_Basic_Sub);
    /// <summary>
    /// Settings_Section_Basic_Title
    /// </summary>
    public const string Settings_Section_Basic_Title = nameof(Settings_Section_Basic_Title);
    /// <summary>
    /// Settings_Section_Combat_Sub
    /// </summary>
    public const string Settings_Section_Combat_Sub = nameof(Settings_Section_Combat_Sub);
    /// <summary>
    /// Settings_Section_Combat_Title
    /// </summary>
    public const string Settings_Section_Combat_Title = nameof(Settings_Section_Combat_Title);
    /// <summary>
    /// Settings_Section_Display_Title
    /// </summary>
    public const string Settings_Section_Display_Title = nameof(Settings_Section_Display_Title);
    /// <summary>
    /// Settings_Section_Language_Description
    /// </summary>
    public const string Settings_Section_Language_Description = nameof(Settings_Section_Language_Description);
    /// <summary>
    /// Settings_Section_Language_Title
    /// </summary>
    public const string Settings_Section_Language_Title = nameof(Settings_Section_Language_Title);
    /// <summary>
    /// Settings_Section_Shortcut_Sub
    /// </summary>
    public const string Settings_Section_Shortcut_Sub = nameof(Settings_Section_Shortcut_Sub);
    /// <summary>
    /// Settings_Section_Shortcut_Title
    /// </summary>
    public const string Settings_Section_Shortcut_Title = nameof(Settings_Section_Shortcut_Title);
    /// <summary>
    /// Settings_Shortcut_ClearData
    /// </summary>
    public const string Settings_Shortcut_ClearData = nameof(Settings_Shortcut_ClearData);
    /// <summary>
    /// Settings_Shortcut_ClearData_Tooltip
    /// </summary>
    public const string Settings_Shortcut_ClearData_Tooltip = nameof(Settings_Shortcut_ClearData_Tooltip);
    /// <summary>
    /// Settings_Shortcut_MouseThrough
    /// </summary>
    public const string Settings_Shortcut_MouseThrough = nameof(Settings_Shortcut_MouseThrough);
    /// <summary>
    /// Settings_Shortcut_MouseThrough_Tooltip
    /// </summary>
    public const string Settings_Shortcut_MouseThrough_Tooltip = nameof(Settings_Shortcut_MouseThrough_Tooltip);
    /// <summary>
    /// Settings_Switch_Off
    /// </summary>
    public const string Settings_Switch_Off = nameof(Settings_Switch_Off);
    /// <summary>
    /// Settings_Switch_On
    /// </summary>
    public const string Settings_Switch_On = nameof(Settings_Switch_On);
    /// <summary>
    /// SkillBreakdown_Card_DamageDistribution
    /// </summary>
    public const string SkillBreakdown_Card_DamageDistribution = nameof(SkillBreakdown_Card_DamageDistribution);
    /// <summary>
    /// SkillBreakdown_Card_RealtimeChart
    /// </summary>
    public const string SkillBreakdown_Card_RealtimeChart = nameof(SkillBreakdown_Card_RealtimeChart);
    /// <summary>
    /// SkillBreakdown_Card_ShareChart
    /// </summary>
    public const string SkillBreakdown_Card_ShareChart = nameof(SkillBreakdown_Card_ShareChart);
    /// <summary>
    /// SkillBreakdown_Header_Title
    /// </summary>
    public const string SkillBreakdown_Header_Title = nameof(SkillBreakdown_Header_Title);
    /// <summary>
    /// SkillBreakdown_Info_Badge
    /// </summary>
    public const string SkillBreakdown_Info_Badge = nameof(SkillBreakdown_Info_Badge);
    /// <summary>
    /// SkillBreakdown_Info_Level
    /// </summary>
    public const string SkillBreakdown_Info_Level = nameof(SkillBreakdown_Info_Level);
    /// <summary>
    /// SkillBreakdown_Info_Name
    /// </summary>
    public const string SkillBreakdown_Info_Name = nameof(SkillBreakdown_Info_Name);
    /// <summary>
    /// SkillBreakdown_Info_Power
    /// </summary>
    public const string SkillBreakdown_Info_Power = nameof(SkillBreakdown_Info_Power);
    /// <summary>
    /// SkillBreakdown_Info_Uid
    /// </summary>
    public const string SkillBreakdown_Info_Uid = nameof(SkillBreakdown_Info_Uid);
    /// <summary>
    /// SkillBreakdown_Label_AverageDamage
    /// </summary>
    public const string SkillBreakdown_Label_AverageDamage = nameof(SkillBreakdown_Label_AverageDamage);
    /// <summary>
    /// SkillBreakdown_Label_CritCount
    /// </summary>
    public const string SkillBreakdown_Label_CritCount = nameof(SkillBreakdown_Label_CritCount);
    /// <summary>
    /// SkillBreakdown_Label_CritDamage
    /// </summary>
    public const string SkillBreakdown_Label_CritDamage = nameof(SkillBreakdown_Label_CritDamage);
    /// <summary>
    /// SkillBreakdown_Label_CritRate
    /// </summary>
    public const string SkillBreakdown_Label_CritRate = nameof(SkillBreakdown_Label_CritRate);
    /// <summary>
    /// SkillBreakdown_Label_DamageTakenCount
    /// </summary>
    public const string SkillBreakdown_Label_DamageTakenCount = nameof(SkillBreakdown_Label_DamageTakenCount);
    /// <summary>
    /// SkillBreakdown_Label_Dps
    /// </summary>
    public const string SkillBreakdown_Label_Dps = nameof(SkillBreakdown_Label_Dps);
    /// <summary>
    /// SkillBreakdown_Label_HitCount
    /// </summary>
    public const string SkillBreakdown_Label_HitCount = nameof(SkillBreakdown_Label_HitCount);
    /// <summary>
    /// SkillBreakdown_Label_LuckCount
    /// </summary>
    public const string SkillBreakdown_Label_LuckCount = nameof(SkillBreakdown_Label_LuckCount);
    /// <summary>
    /// SkillBreakdown_Label_LuckDamage
    /// </summary>
    public const string SkillBreakdown_Label_LuckDamage = nameof(SkillBreakdown_Label_LuckDamage);
    /// <summary>
    /// SkillBreakdown_Label_LuckRate
    /// </summary>
    public const string SkillBreakdown_Label_LuckRate = nameof(SkillBreakdown_Label_LuckRate);
    /// <summary>
    /// SkillBreakdown_Label_NormalDamage
    /// </summary>
    public const string SkillBreakdown_Label_NormalDamage = nameof(SkillBreakdown_Label_NormalDamage);
    /// <summary>
    /// SkillBreakdown_Label_TotalDamage
    /// </summary>
    public const string SkillBreakdown_Label_TotalDamage = nameof(SkillBreakdown_Label_TotalDamage);
    /// <summary>
    /// SkillBreakdown_Placeholder_BarChart
    /// </summary>
    public const string SkillBreakdown_Placeholder_BarChart = nameof(SkillBreakdown_Placeholder_BarChart);
    /// <summary>
    /// SkillBreakdown_Placeholder_Details
    /// </summary>
    public const string SkillBreakdown_Placeholder_Details = nameof(SkillBreakdown_Placeholder_Details);
    /// <summary>
    /// SkillBreakdown_Placeholder_Form
    /// </summary>
    public const string SkillBreakdown_Placeholder_Form = nameof(SkillBreakdown_Placeholder_Form);
    /// <summary>
    /// SkillBreakdown_Placeholder_Graph
    /// </summary>
    public const string SkillBreakdown_Placeholder_Graph = nameof(SkillBreakdown_Placeholder_Graph);
    /// <summary>
    /// SkillBreakdown_Placeholder_LineChart
    /// </summary>
    public const string SkillBreakdown_Placeholder_LineChart = nameof(SkillBreakdown_Placeholder_LineChart);
    /// <summary>
    /// SkillBreakdown_Placeholder_PieChart
    /// </summary>
    public const string SkillBreakdown_Placeholder_PieChart = nameof(SkillBreakdown_Placeholder_PieChart);
    /// <summary>
    /// SkillBreakdown_Section_DamageDistribution
    /// </summary>
    public const string SkillBreakdown_Section_DamageDistribution = nameof(SkillBreakdown_Section_DamageDistribution);
    /// <summary>
    /// SkillBreakdown_Section_DamageInfo
    /// </summary>
    public const string SkillBreakdown_Section_DamageInfo = nameof(SkillBreakdown_Section_DamageInfo);
    /// <summary>
    /// SkillBreakdown_Tab_Details
    /// </summary>
    public const string SkillBreakdown_Tab_Details = nameof(SkillBreakdown_Tab_Details);
    /// <summary>
    /// SkillBreakdown_Tab_Graph
    /// </summary>
    public const string SkillBreakdown_Tab_Graph = nameof(SkillBreakdown_Tab_Graph);
    /// <summary>
    /// SkillBreakdown_Tab_Healing
    /// </summary>
    public const string SkillBreakdown_Tab_Healing = nameof(SkillBreakdown_Tab_Healing);
    /// <summary>
    /// SkillBreakdown_Tab_Output
    /// </summary>
    public const string SkillBreakdown_Tab_Output = nameof(SkillBreakdown_Tab_Output);
    /// <summary>
    /// SkillBreakdown_Tab_Summary
    /// </summary>
    public const string SkillBreakdown_Tab_Summary = nameof(SkillBreakdown_Tab_Summary);
    /// <summary>
    /// SkillBreakdown_Tab_Tanking
    /// </summary>
    public const string SkillBreakdown_Tab_Tanking = nameof(SkillBreakdown_Tab_Tanking);
    /// <summary>
    /// SkillBreakdown_Value_AverageDamage
    /// </summary>
    public const string SkillBreakdown_Value_AverageDamage = nameof(SkillBreakdown_Value_AverageDamage);
    /// <summary>
    /// SkillBreakdown_Value_CritCount
    /// </summary>
    public const string SkillBreakdown_Value_CritCount = nameof(SkillBreakdown_Value_CritCount);
    /// <summary>
    /// SkillBreakdown_Value_CritDamage
    /// </summary>
    public const string SkillBreakdown_Value_CritDamage = nameof(SkillBreakdown_Value_CritDamage);
    /// <summary>
    /// SkillBreakdown_Value_CritRate
    /// </summary>
    public const string SkillBreakdown_Value_CritRate = nameof(SkillBreakdown_Value_CritRate);
    /// <summary>
    /// SkillBreakdown_Value_DamageTakenCount
    /// </summary>
    public const string SkillBreakdown_Value_DamageTakenCount = nameof(SkillBreakdown_Value_DamageTakenCount);
    /// <summary>
    /// SkillBreakdown_Value_Dps
    /// </summary>
    public const string SkillBreakdown_Value_Dps = nameof(SkillBreakdown_Value_Dps);
    /// <summary>
    /// SkillBreakdown_Value_HitCount
    /// </summary>
    public const string SkillBreakdown_Value_HitCount = nameof(SkillBreakdown_Value_HitCount);
    /// <summary>
    /// SkillBreakdown_Value_LuckCount
    /// </summary>
    public const string SkillBreakdown_Value_LuckCount = nameof(SkillBreakdown_Value_LuckCount);
    /// <summary>
    /// SkillBreakdown_Value_LuckDamage
    /// </summary>
    public const string SkillBreakdown_Value_LuckDamage = nameof(SkillBreakdown_Value_LuckDamage);
    /// <summary>
    /// SkillBreakdown_Value_LuckRate
    /// </summary>
    public const string SkillBreakdown_Value_LuckRate = nameof(SkillBreakdown_Value_LuckRate);
    /// <summary>
    /// SkillBreakdown_Value_NormalDamage
    /// </summary>
    public const string SkillBreakdown_Value_NormalDamage = nameof(SkillBreakdown_Value_NormalDamage);
    /// <summary>
    /// SkillBreakdown_Value_TotalDamage
    /// </summary>
    public const string SkillBreakdown_Value_TotalDamage = nameof(SkillBreakdown_Value_TotalDamage);
    /// <summary>
    /// Tooltip_ToggleScope
    /// </summary>
    public const string Tooltip_ToggleScope = nameof(Tooltip_ToggleScope);
    /// <summary>
    /// Window_About_Title
    /// </summary>
    public const string Window_About_Title = nameof(Window_About_Title);
    /// <summary>
    /// Window_DamageReference_Title
    /// </summary>
    public const string Window_DamageReference_Title = nameof(Window_DamageReference_Title);
    /// <summary>
    /// Window_Debug_Title
    /// </summary>
    public const string Window_Debug_Title = nameof(Window_Debug_Title);
    /// <summary>
    /// Window_DpsStatistics_Title
    /// </summary>
    public const string Window_DpsStatistics_Title = nameof(Window_DpsStatistics_Title);
    /// <summary>
    /// Window_ModuleSolve_Title
    /// </summary>
    public const string Window_ModuleSolve_Title = nameof(Window_ModuleSolve_Title);
    /// <summary>
    /// Window_Settings_Title
    /// </summary>
    public const string Window_Settings_Title = nameof(Window_Settings_Title);
    /// <summary>
    /// Window_SkillBreakdown_Title
    /// </summary>
    public const string Window_SkillBreakdown_Title = nameof(Window_SkillBreakdown_Title);
}
