//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarResonanceDpsAnalysis.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarResonanceDpsAnalysis.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 678150498（1群） 的本地化字符串。
        /// </summary>
        public static string About_Community_GroupOne {
            get {
                return ResourceManager.GetString("About_Community_GroupOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1022797551（2群） 的本地化字符串。
        /// </summary>
        public static string About_Community_GroupTwo {
            get {
                return ResourceManager.GetString("About_Community_GroupTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法访问 GitHub 或者想要寻求游戏伙伴也可以加QQ群： 的本地化字符串。
        /// </summary>
        public static string About_Community_Invite {
            get {
                return ResourceManager.GetString("About_Community_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果你想为本项目贡献代码，欢迎 Fork 之后提交 Pull Request。 的本地化字符串。
        /// </summary>
        public static string About_Contribution {
            get {
                return ResourceManager.GetString("About_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (C) 2025 anying1073/StarResonanceDps Team. 的本地化字符串。
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尻鸭（ihonliu） 的本地化字符串。
        /// </summary>
        public static string About_Developer_Ihonliu {
            get {
                return ResourceManager.GetString("About_Developer_Ihonliu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 惊奇猫猫盒（anying1073：项目发起者） 的本地化字符串。
        /// </summary>
        public static string About_Developer_Lead {
            get {
                return ResourceManager.GetString("About_Developer_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青岚宗王腾 的本地化字符串。
        /// </summary>
        public static string About_Developer_QingLan {
            get {
                return ResourceManager.GetString("About_Developer_QingLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 露詩（Rocy-June） 的本地化字符串。
        /// </summary>
        public static string About_Developer_RocyJune {
            get {
                return ResourceManager.GetString("About_Developer_RocyJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本的开发者们（排名不分先后）: 的本地化字符串。
        /// </summary>
        public static string About_Developers_Label {
            get {
                return ResourceManager.GetString("About_Developers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该工具无需修改游戏客户端，不违反游戏服务条款。该工具旨在帮助玩家更好地理解战斗数据，减少不必要的精力消耗，提升游戏体验。使用该工具前，请确保不会将数据结果用于战力歧视等破坏游戏社区环境的行为。 的本地化字符串。
        /// </summary>
        public static string About_Intro_Details {
            get {
                return ResourceManager.GetString("About_Intro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一款专为《星痕共鸣》玩家打造的战斗数据统计工具。 的本地化字符串。
        /// </summary>
        public static string About_Intro_Primary {
            get {
                return ResourceManager.GetString("About_Intro_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本项目于 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_Prefix {
            get {
                return ResourceManager.GetString("About_OpenSource_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/anying1073/StarResonanceDps 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_OpenSource_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中开源，如在使用中遇到问题可以直接提出 Issue。 的本地化字符串。
        /// </summary>
        public static string About_OpenSource_Suffix {
            get {
                return ResourceManager.GetString("About_OpenSource_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by .NET 8, Licensed under the GNU AGPL v3. 的本地化字符串。
        /// </summary>
        public static string About_PoweredBy {
            get {
                return ResourceManager.GetString("About_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此感谢 的本地化字符串。
        /// </summary>
        public static string About_Thanks_Prefix {
            get {
                return ResourceManager.GetString("About_Thanks_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/dmlgzs/StarResonanceDamageCounter 的本地化字符串。
        /// </summary>
        public static string About_Thanks_RepositoryUrl {
            get {
                return ResourceManager.GetString("About_Thanks_RepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目对于本项目的帮助于支持 的本地化字符串。
        /// </summary>
        public static string About_Thanks_Suffix {
            get {
                return ResourceManager.GetString("About_Thanks_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本号： 的本地化字符串。
        /// </summary>
        public static string About_Version_Label {
            get {
                return ResourceManager.GetString("About_Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别查我DPS 的本地化字符串。
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        public static string Common_Action_Open {
            get {
                return ResourceManager.GetString("Common_Action_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string Common_Dash {
            get {
                return ResourceManager.GetString("Common_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以上数据仅供娱乐与参考，严禁用于战力歧视等破坏游戏社区环境的行为；一经发现，永久取消该功能的使用资格。 的本地化字符串。
        /// </summary>
        public static string DamageReference_Disclaimer {
            get {
                return ResourceManager.GetString("DamageReference_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill Breakdown 的本地化字符串。
        /// </summary>
        public static string DamageReference_Header_Title {
            get {
                return ResourceManager.GetString("DamageReference_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据 的本地化字符串。
        /// </summary>
        public static string DamageReference_NoData {
            get {
                return ResourceManager.GetString("DamageReference_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全职业 的本地化字符串。
        /// </summary>
        public static string DamageReference_Profession_All {
            get {
                return ResourceManager.GetString("DamageReference_Profession_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害参考 的本地化字符串。
        /// </summary>
        public static string DamageReference_Ribbon_Title {
            get {
                return ResourceManager.GetString("DamageReference_Ribbon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害参考 的本地化字符串。
        /// </summary>
        public static string DamageReference_Table_Title {
            get {
                return ResourceManager.GetString("DamageReference_Table_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddSampleData 的本地化字符串。
        /// </summary>
        public static string Debug_AddSampleData {
            get {
                return ResourceManager.GetString("Debug_AddSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Test Log 的本地化字符串。
        /// </summary>
        public static string Debug_AddTestLog {
            get {
                return ResourceManager.GetString("Debug_AddTestLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Scroll 的本地化字符串。
        /// </summary>
        public static string Debug_AutoScroll {
            get {
                return ResourceManager.GetString("Debug_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于窗口 的本地化字符串。
        /// </summary>
        public static string Debug_Button_About {
            get {
                return ResourceManager.GetString("Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害参考窗口 的本地化字符串。
        /// </summary>
        public static string Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pcap 测试 的本地化字符串。
        /// </summary>
        public static string Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置窗口 的本地化字符串。
        /// </summary>
        public static string Debug_Button_Settings {
            get {
                return ResourceManager.GetString("Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能详情窗口 的本地化字符串。
        /// </summary>
        public static string Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Logs 的本地化字符串。
        /// </summary>
        public static string Debug_ClearLogs {
            get {
                return ResourceManager.GetString("Debug_ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter: 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Label {
            get {
                return ResourceManager.GetString("Debug_Filter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Level {
            get {
                return ResourceManager.GetString("Debug_Filter_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter logs by message or category content 的本地化字符串。
        /// </summary>
        public static string Debug_Filter_Tooltip {
            get {
                return ResourceManager.GetString("Debug_Filter_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试功能 的本地化字符串。
        /// </summary>
        public static string Debug_Group_Title {
            get {
                return ResourceManager.GetString("Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Category {
            get {
                return ResourceManager.GetString("Debug_Header_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Level {
            get {
                return ResourceManager.GetString("Debug_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Message {
            get {
                return ResourceManager.GetString("Debug_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string Debug_Header_Time {
            get {
                return ResourceManager.GetString("Debug_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load PCAP 的本地化字符串。
        /// </summary>
        public static string Debug_LoadPcap {
            get {
                return ResourceManager.GetString("Debug_LoadPcap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Logs 的本地化字符串。
        /// </summary>
        public static string Debug_SaveLogs {
            get {
                return ResourceManager.GetString("Debug_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤： 的本地化字符串。
        /// </summary>
        public static string Debug_Status_FilteredPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条日志 的本地化字符串。
        /// </summary>
        public static string Debug_Status_FilteredSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_FilteredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新： 的本地化字符串。
        /// </summary>
        public static string Debug_Status_LastPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_LastPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计： 的本地化字符串。
        /// </summary>
        public static string Debug_Status_TotalPrefix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  条日志 的本地化字符串。
        /// </summary>
        public static string Debug_Status_TotalSuffix {
            get {
                return ResourceManager.GetString("Debug_Status_TotalSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题切换测试文本 的本地化字符串。
        /// </summary>
        public static string Debug_ThemeTestText {
            get {
                return ResourceManager.GetString("Debug_ThemeTestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_TestButton_Content {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加测试数据 的本地化字符串。
        /// </summary>
        public static string DpsStatistics_TestButton_Tooltip {
            get {
                return ResourceManager.GetString("DpsStatistics_TestButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于窗口 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Button_About {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害参考窗口 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Button_DamageReference {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_DamageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pcap 测试 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Button_PcapTest {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_PcapTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置窗口 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Button_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能详情窗口 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Button_SkillBreakdown {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Button_SkillBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试功能 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_Group_Title {
            get {
                return ResourceManager.GetString("MainWindow_Debug_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题切换测试文本 的本地化字符串。
        /// </summary>
        public static string MainWindow_Debug_ThemeTest {
            get {
                return ResourceManager.GetString("MainWindow_Debug_ThemeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别查我 D P S 的本地化字符串。
        /// </summary>
        public static string MainWindow_Header_Title {
            get {
                return ResourceManager.GetString("MainWindow_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [官方] 别查我DPS 开发团队 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Author_OfficialTeam {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Author_OfficialTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自启动 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_AutoStart {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供DPS统计、技能分解等功能 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_DpsTool_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_DpsTool_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS工具 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_DpsTool_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_DpsTool_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者： 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Label_Author {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Label_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介： 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_Label_Intro {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_Label_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供模组快速计算最优解功能 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_ModuleSolver_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_ModuleSolver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组求解器 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_ModuleSolver_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_ModuleSolver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过大量的玩家在线数据互助，提供小猪娜宝的线路与位置信息 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_PigTracker_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_PigTracker_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小猪娜宝状态查看器 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_PigTracker_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_PigTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过大量的玩家在线数据互助，提供各线路的野外BOSS存活状态等信息 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_WorldBoss_Description {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_WorldBoss_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 野外BOSS状态查看器 的本地化字符串。
        /// </summary>
        public static string MainWindow_Plugin_WorldBoss_Title {
            get {
                return ResourceManager.GetString("MainWindow_Plugin_WorldBoss_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件列表 的本地化字符串。
        /// </summary>
        public static string MainWindow_PluginList_Title {
            get {
                return ResourceManager.GetString("MainWindow_PluginList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录 的本地化字符串。
        /// </summary>
        public static string Menu_History {
            get {
                return ResourceManager.GetString("Menu_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人模式 的本地化字符串。
        /// </summary>
        public static string Menu_PersonalMode {
            get {
                return ResourceManager.GetString("Menu_PersonalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录每一次 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Always {
            get {
                return ResourceManager.GetString("Menu_Record_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不记录1分钟以下 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Skip1Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip1Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不记录2分钟以下 的本地化字符串。
        /// </summary>
        public static string Menu_Record_Skip2Min {
            get {
                return ResourceManager.GetString("Menu_Record_Skip2Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录设置 的本地化字符串。
        /// </summary>
        public static string Menu_RecordSettings {
            get {
                return ResourceManager.GetString("Menu_RecordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示总伤 的本地化字符串。
        /// </summary>
        public static string Menu_ShowTotal {
            get {
                return ResourceManager.GetString("Menu_ShowTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能日记 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDiary {
            get {
                return ResourceManager.GetString("Menu_SkillDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能显示 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示全部 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_All {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 10 条 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top10 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 15 条 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top15 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 5 条 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top5 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前 8 条 的本地化字符串。
        /// </summary>
        public static string Menu_SkillDisplay_Top8 {
            get {
                return ResourceManager.GetString("Menu_SkillDisplay_Top8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计BOSS 的本地化字符串。
        /// </summary>
        public static string Menu_StatisticBoss {
            get {
                return ResourceManager.GetString("Menu_StatisticBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打桩模式 的本地化字符串。
        /// </summary>
        public static string Menu_Training {
            get {
                return ResourceManager.GetString("Menu_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极限打桩 的本地化字符串。
        /// </summary>
        public static string Menu_Training_Extreme {
            get {
                return ResourceManager.GetString("Menu_Training_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协会打桩 的本地化字符串。
        /// </summary>
        public static string Menu_Training_Faction {
            get {
                return ResourceManager.GetString("Menu_Training_Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人打桩 的本地化字符串。
        /// </summary>
        public static string Menu_Training_Personal {
            get {
                return ResourceManager.GetString("Menu_Training_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分析模组 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Analyze_Button {
            get {
                return ResourceManager.GetString("ModuleSolve_Analyze_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排除词条（与目标词条冲突）[可输入文字索引] 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ExcludeProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_ExcludeProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 期望等级： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ExpectedLevel_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ExpectedLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组求解器 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Header_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_All {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防御模组 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Defense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组类型： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 攻击模组 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Offense {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Offense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅助模组 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_ModuleType_Support {
            get {
                return ResourceManager.GetString("ModuleSolve_ModuleType_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性1： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property1_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性2： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property2_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性3： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property3_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性4： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property4_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性5： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Property5_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Property5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性优先 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Attribute {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序方式： 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Label {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级优先 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_Sort_Level {
            get {
                return ResourceManager.GetString("ModuleSolve_Sort_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标词条和等级（0为默认）[可输入文字索引] 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_TargetProperties_Title {
            get {
                return ResourceManager.GetString("ModuleSolve_TargetProperties_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开此界面后需要过图或者重新登陆一次才能进行分析【右键属性选项为清空当前选项】 的本地化字符串。
        /// </summary>
        public static string ModuleSolve_UsingTip {
            get {
                return ResourceManager.GetString("ModuleSolve_UsingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三位计数法 (KMBT) 的本地化字符串。
        /// </summary>
        public static string NumberDisplay_KMB {
            get {
                return ResourceManager.GetString("NumberDisplay_KMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四位计数法 (万亿兆) 的本地化字符串。
        /// </summary>
        public static string NumberDisplay_Wan {
            get {
                return ResourceManager.GetString("NumberDisplay_Wan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰魔导师 的本地化字符串。
        /// </summary>
        public static string Profession_FrostMage {
            get {
                return ResourceManager.GetString("Profession_FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 巨刃守护者 的本地化字符串。
        /// </summary>
        public static string Profession_HeavyGuardian {
            get {
                return ResourceManager.GetString("Profession_HeavyGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神射手 的本地化字符串。
        /// </summary>
        public static string Profession_Marksman {
            get {
                return ResourceManager.GetString("Profession_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神盾骑士 的本地化字符串。
        /// </summary>
        public static string Profession_ShieldKnight {
            get {
                return ResourceManager.GetString("Profession_ShieldKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灵魂乐手 的本地化字符串。
        /// </summary>
        public static string Profession_SoulMusician {
            get {
                return ResourceManager.GetString("Profession_SoulMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷影剑士 的本地化字符串。
        /// </summary>
        public static string Profession_Stormblade {
            get {
                return ResourceManager.GetString("Profession_Stormblade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 森语者 的本地化字符串。
        /// </summary>
        public static string Profession_VerdantOracle {
            get {
                return ResourceManager.GetString("Profession_VerdantOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青岚骑士 的本地化字符串。
        /// </summary>
        public static string Profession_WindKnight {
            get {
                return ResourceManager.GetString("Profession_WindKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前 的本地化字符串。
        /// </summary>
        public static string ScopeTime_Current {
            get {
                return ResourceManager.GetString("ScopeTime_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全程 的本地化字符串。
        /// </summary>
        public static string ScopeTime_Total {
            get {
                return ResourceManager.GetString("ScopeTime_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脱战后清除当前统计 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_ClearAfterBattle {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换地图时清空全程统计 的本地化字符串。
        /// </summary>
        public static string Settings_Combat_ClearAfterTeleport {
            get {
                return ResourceManager.GetString("Settings_Combat_ClearAfterTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Settings_Common_Seconds {
            get {
                return ResourceManager.GetString("Settings_Common_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数显示类型 的本地化字符串。
        /// </summary>
        public static string Settings_Display_NumberMode {
            get {
                return ResourceManager.GetString("Settings_Display_NumberMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗体透明度 的本地化字符串。
        /// </summary>
        public static string Settings_Display_Opacity {
            get {
                return ResourceManager.GetString("Settings_Display_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings_Heading {
            get {
                return ResourceManager.GetString("Settings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Auto {
            get {
                return ResourceManager.GetString("Settings_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Settings_Language_Chinese {
            get {
                return ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听网卡 的本地化字符串。
        /// </summary>
        public static string Settings_NetworkAdapter_Label {
            get {
                return ResourceManager.GetString("Settings_NetworkAdapter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动设置错误时可手动设置 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Basic_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础设置 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Basic_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Basic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脱战清空只重置当前战斗数据，而非全程统计 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Combat_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战斗设置 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Combat_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Combat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示设置 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Display_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择界面语言 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Language_Description {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Language_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 Delete 删除选择的键位 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Shortcut_Sub {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键设置 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Shortcut_Title {
            get {
                return ResourceManager.GetString("Settings_Section_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空数据 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ClearData {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此聚焦并按下快捷键（例如 F9）。按 Delete 清除。 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_ClearData_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_ClearData_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标穿透 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_MouseThrough {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此聚焦并按下组合键（例如 Ctrl+F6）。按 Delete 清除。 的本地化字符串。
        /// </summary>
        public static string Settings_Shortcut_MouseThrough_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Shortcut_MouseThrough_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        public static string Settings_Switch_Off {
            get {
                return ResourceManager.GetString("Settings_Switch_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        public static string Settings_Switch_On {
            get {
                return ResourceManager.GetString("Settings_Switch_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害分布 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DPS/HPS/DTPS实时曲线图 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_RealtimeChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_RealtimeChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能占比分布图 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Card_ShareChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Card_ShareChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能详情 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Header_Title {
            get {
                return ResourceManager.GetString("SkillBreakdown_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 臂章: 190 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Badge {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级: 60 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Level {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --测试名称-- 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Name {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战力: 25000 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Power {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UID: 123456 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Info_Uid {
            get {
                return ResourceManager.GetString("SkillBreakdown_Info_Uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均伤害 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击次数 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击伤害 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击率 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 受击次数 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒伤 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命中次数 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运次数 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运伤害 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运率 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通伤害 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总伤害 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Label_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Label_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假装这里有个条形图 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_BarChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_BarChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情占位 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假装这里有个表单 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Form {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表占位 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假装这里有个折线图 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_LineChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假装这里有个饼图 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Placeholder_PieChart {
            get {
                return ResourceManager.GetString("SkillBreakdown_Placeholder_PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害分布 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Section_DamageDistribution {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害信息 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Section_DamageInfo {
            get {
                return ResourceManager.GetString("SkillBreakdown_Section_DamageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Details {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Graph {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Healing {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Output {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Summary 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Summary {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承伤 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Tab_Tanking {
            get {
                return ResourceManager.GetString("SkillBreakdown_Tab_Tanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7106 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_AverageDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_AverageDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 13.92K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 16.67% 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_CritRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_DamageTakenCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_DamageTakenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 29.01K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_Dps {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_Dps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_HitCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckCount {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0% 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_LuckRate {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_LuckRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 28.71K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_NormalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_NormalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 42.64K 的本地化字符串。
        /// </summary>
        public static string SkillBreakdown_Value_TotalDamage {
            get {
                return ResourceManager.GetString("SkillBreakdown_Value_TotalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害 的本地化字符串。
        /// </summary>
        public static string StatisticType_Damage {
            get {
                return ResourceManager.GetString("StatisticType_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗 的本地化字符串。
        /// </summary>
        public static string StatisticType_Healing {
            get {
                return ResourceManager.GetString("StatisticType_Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NPC承伤 的本地化字符串。
        /// </summary>
        public static string StatisticType_NpcTakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_NpcTakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 承伤 的本地化字符串。
        /// </summary>
        public static string StatisticType_TakenDamage {
            get {
                return ResourceManager.GetString("StatisticType_TakenDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换为：全程 / 当前 的本地化字符串。
        /// </summary>
        public static string Tooltip_ToggleScope {
            get {
                return ResourceManager.GetString("Tooltip_ToggleScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Window_About_Title {
            get {
                return ResourceManager.GetString("Window_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 野外Boss状态查看器 的本地化字符串。
        /// </summary>
        public static string Window_BossTracker_Title {
            get {
                return ResourceManager.GetString("Window_BossTracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害参考 的本地化字符串。
        /// </summary>
        public static string Window_DamageReference_Title {
            get {
                return ResourceManager.GetString("Window_DamageReference_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug View 的本地化字符串。
        /// </summary>
        public static string Window_Debug_Title {
            get {
                return ResourceManager.GetString("Window_Debug_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DpsStatisticsForm 的本地化字符串。
        /// </summary>
        public static string Window_DpsStatistics_Title {
            get {
                return ResourceManager.GetString("Window_DpsStatistics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组求解器 的本地化字符串。
        /// </summary>
        public static string Window_ModuleSolve_Title {
            get {
                return ResourceManager.GetString("Window_ModuleSolve_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Window_Settings_Title {
            get {
                return ResourceManager.GetString("Window_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 技能详情 的本地化字符串。
        /// </summary>
        public static string Window_SkillBreakdown_Title {
            get {
                return ResourceManager.GetString("Window_SkillBreakdown_Title", resourceCulture);
            }
        }
    }
}
