name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore StarResonanceDpsAnalysis.sln --runtime win-x64

    - name: Build solution
      run: dotnet build StarResonanceDpsAnalysis.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test StarResonanceDpsAnalysis.sln --configuration ${{ matrix.configuration }} --no-build

    - name: Publish WPF application
      run: |
        dotnet publish StarResonanceDpsAnalysis.WPF/StarResonanceDpsAnalysis.WPF.csproj `
          --configuration ${{ matrix.configuration }} `
          --runtime win-x64 `
          --output ./publish `
          -p:PublishSingleFile=true `
          -p:IncludeAllContentForSelfExtract=true `
          --self-contained false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: StarResonanceDpsAnalysis-${{ matrix.configuration }}
        path: |
          ./publish/**/*.exe
          ./publish/**/*.dll
        retention-days: 30
